# Generated by Django 5.0.7 on 2024-07-25 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('flatpages', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='flatpages.flatpage')),
            ],
        ),
    ]
